### ISSUE TITLE
embedding_dim doesn't appear to do anything in Brain()

### ISSUE THREAD

**Issue by Zach-Attach** [buildingamind/NewbornEmbodiedTuringTest#16]
**Describe the bug**
`embedding_dim` doesn't appear to be used anywhere.

**To Reproduce**
See search of code here: https://github.com/search?q=repo%3Abuildingamind%2FNewbornEmbodiedTuringTest%20embedding_dim&type=code

**Expected behavior**
embedding_dim should determine the number of dimensions in embedding vectors

**Comment by desaibhargav** [comment]
Hi @Zach-Attach, the `embedding_dim` argument corresponds to the output dimensionality of the encoder network (often, the number of neurons in the last layer of the network) and is for when a user wants to pass custom encoders. For encoders that the package provides out-of-the-box, `embedding_dim` is determined automatically and hence a `None` value is accepted too. 

Does this help?

**Comment by Zach-Attach** [comment]
Looks like it needs to be implemented in Line 118 in brain/builder.py

**Comment by Zach-Attach** [comment]
Closing. This was fixed.
