### ISSUE TITLE
Orphaned processes appear to stay in memory 

### ISSUE THREAD

**Issue by Zach-Attach** [buildingamind/NewbornEmbodiedTuringTest#30]
**Describe the bug**
Looking at the servers, it appears that the python and executable processes stay in memory when not running. This may be a result of closing processes early or it may be a result of processes not closing after completing.

**Comment by desaibhargav** [comment]
I tested this and it is indeed that processes are staying back in the memory after finishing execution. I created a branch for [this](https://github.com/buildingamind/NewbornEmbodiedTuringTest/tree/fix/close-out-processes). This will be part of the upcoming major release v0.2. 

Thanks for reporting this @Zach-Attach

**Comment by Zach-Attach** [comment]
Closing. Fixed by closing GymEnvironments from linked PR.
