### ISSUE TITLE
Enforce Branch Protection

### ISSUE THREAD

**Issue by Zach-Attach** [buildingamind/NewbornEmbodiedTuringTest#7]
Direct pushes to `main`, `dev`, and `gh-pages` should not be allowed, forcing Pull Requests and review from another person before being able to make any changes to these branches. See [this link](https://johnnymetz.com/posts/disable-direct-push-to-main-branch/) for instructions on how to do so.

A suggested system might be the following:
- `dev` requires PR approval from another person in the lab
- `main` and `gh-pages` requires PR approval from a higher authorization (those with higher repo control, moderators? Or something of the like)

This is merely a suggestion of how it could be enforced, but branch protection would help to prevent accidental changes to important branches of code.

**Comment by desaibhargav** [comment]
Hi @Zach-Attach, thanks for raising this issue. As you correctly out, branch protection is important for any collaborative project, such as ours. Currently, the `main` branch is protected--direct commits will be rejected and all PRs will need approval from the repository owners. I agree with `dev` and `gh-pages` needing protection too. 

You have admin access to the repository, please feel free to add any additional rules that you see fit. I'll review them soon.

**Comment by desaibhargav** [comment]
Reopening this as I've deleted the `dev` and created a new `develop` to fix the alignment issues with `main`. Could you add protection rules again for `develop`? 

We can rename this to `dev` too.

**Comment by Zach-Attach** [comment]
Renamed to `dev`. Also added branch protection to it
