### ISSUE TITLE
Environment.list_configs() results in an AttributeError

### ISSUE THREAD

**Issue by camiclar** [buildingamind/NewbornEmbodiedTuringTest#88]
**Describe the bug**
Running "Environment.list_configs()" in a Jupyter Notebook produces the following error: type object 'Environment' has no attribute 'list_configs'

**To Reproduce**
Follow "Running a NETT" instructions under "Getting Started" in the readme, using Jupyter Notebook to run the commands. Run the import commands, then "Environment.list_configs()".

**Expected behavior**
A list of available configurations is outputted.

**Screenshots**
![Screenshot 2024-04-09 201442](https://github.com/buildingamind/NewbornEmbodiedTuringTest/assets/77860412/a13e2a99-fc0b-45d8-8193-16123549cad2)

**Desktop:**
 - OS: Ubuntu via Windows Susbsystem for Linux, base system is Windows 11

**Additional context**
I installed jupyter using "conda install jupyter," then when trying to launch notebook, got the error: ModuleNotFoundError: No module named 'chardet'. I then ran "conda install -c conda-forge chardet" which allowed me to run notebook. Not sure if that has anything to do with this issue.

**Comment by Zach-Attach** [comment]
It appears that the modules nett.environment nett.brain etc contain these list functions, so we will just move these functions to be directly under nett
